<?php


namespace HuanL\Verify\Tests;

use HuanL\Verify\Rule;
use HuanL\Verify\Verify;
use PHPUnit\Framework\TestCase;

require_once './../src/Verify.php';
require_once './../src/Rule.php';

class VerifyTest extends TestCase {

    /**
     * @var Verify
     */
    protected $verify = null;

    protected function setUp()/* The :void return type declaration that should be here would cause a BC issue */ {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->verify = new Verify();
    }

    public function testMultiRule() {
        $this->verify->addData([
            'empty' => '123', 'user' => 'aaa'
        ]);
        $this->verify->addRule([
            'empty' => ['empty' => [false, '233']],
            'user' => ['empty' => false]
        ]);
        self::assertEquals($this->verify->check(), true);
        self::assertEquals(sizeof($this->verify->getErrorList()), 0);
        self::assertEquals($this->verify->getLastError(), null);
    }

    public function testMultiRule1() {
        $this->verify->addData([
            'empty' => '', 'user' => 'aaa'
        ]);
        $this->verify->addRule([
            'empty' => ['empty' => [false, '233']],
            'user' => ['empty' => false]
        ]);
        self::assertEquals($this->verify->check(), false);
        self::assertEquals(sizeof($this->verify->getErrorList()), 1);
        self::assertEquals($this->verify->getLastError(), '233');
    }

    public function testMultiRule2() {
        $this->verify->addData([
            'empty' => '', 'user' => ''
        ]);
        $this->verify->addRule([
            'empty' => ['empty' => [false, '233']],
            'user' => ['empty' => false]
        ]);
        self::assertEquals($this->verify->check(false), false);
        self::assertEquals(sizeof($this->verify->getErrorList()), 2);
        self::assertEquals($this->verify->getLastError(), 'user不能为空');
        self::assertEquals($this->verify->getLastError(), '233');
    }

    public function testEmpty() {
        $this->verify->addData('emp', '');
        $this->verify->addRule('emp')->empty();
        self::assertEquals($this->verify->check(), true);
    }

    public function testEmpty1() {
        $a = new Rule();
        $this->verify->addRule('emp')->empty(false, function () use ($a) {
            return $a;
        });
        self::assertEquals($this->verify->check(), false);
        self::assertEquals($this->verify->getLastError(), $a);
    }

    public function testEmpty2() {
        $this->verify->addData('emp', '');
        $this->verify->addRule('emp')->empty(false, '错误信息');
        self::assertEquals($this->verify->check(), false);
        self::assertEquals($this->verify->getLastError(), '错误信息');
    }

    public function testEmpty3() {
        $this->verify->addData('emp', '123');
        $this->verify->addRule('emp')->empty(false);
        self::assertEquals($this->verify->check(), true);
    }

    public function testEmpty4() {
        $this->verify->addRule('emp')->empty();
        self::assertEquals($this->verify->check(), true);
    }
}
