<?php


namespace HuanL\Verify\Tests;

use HuanL\Verify\Verify;
use PHPUnit\Framework\TestCase;

require_once './../src/Verify.php';
require_once './../src/Rule.php';

class VerifyTest extends TestCase {

    /**
     * @var Verify
     */
    protected $verify = null;

    protected function setUp()/* The :void return type declaration that should be here would cause a BC issue */ {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->verify = new Verify();
    }

    public function testEmpty() {
        $this->verify->addData('emp', '');
        $this->verify->addRule('emp')->empty();
        self::assertEquals($this->verify->check(), true);
    }

    public function testEmpty1() {
        $this->verify->addRule('emp')->empty(false);
        self::assertEquals($this->verify->check(), false);
    }

    public function testEmpty2() {
        $this->verify->addData('emp', '');
        $this->verify->addRule('emp')->empty(false);
        self::assertEquals($this->verify->check(), false);
    }

    public function testEmpty3() {
        $this->verify->addData('emp', '123');
        $this->verify->addRule('emp')->empty(false);
        self::assertEquals($this->verify->check(), true);
    }

    public function testEmpty4() {
        $this->verify->addRule('emp')->empty();
        self::assertEquals($this->verify->check(), true);
    }
}
